version: '3.7'

services:
  app:
    build: .
    ports:
      - ${RAILS_PORT:-3000}:3000
    volumes:
      - .:/app
    command: bundle exec rails server -b 0.0.0.0
    tty: true
    stdin_open: true
